export const RECEIVE_MENU_REQUEST = Symbol("RECEIVE_MENU_REQUEST");
export const RECEIVE_MENU_SUCCESS = Symbol("RECEIVE_MENU_SUCCESS");
export const RECEIVE_MENU_FAILURE = Symbol("RECEIVE_MENU_FAILURE");

