export const RECEIVE_MENU_REQUEST = Symbol("RECEIVE_MENU_REQUEST");
export const RECEIVE_MENU_SUCCESS = Symbol("RECEIVE_MENU_SUCCESS");
export const RECEIVE_MENU_FAILURE = Symbol("RECEIVE_MENU_FAILURE");
export const RECEIVE_ADDONS_SUCCESS = Symbol("RECEIVE_MENU_SUCCESS");
export const RECEIVE_ADDONS_FAILURE = Symbol("RECEIVE_MENU_FAILURE");
export const RECEIVE_COFFEEHOUSES_SUCCESS = Symbol("RECEIVE_COFFEEHOUSES_SUCCESS");
export const RECEIVE_COFFEEHOUSES_FAILURE = Symbol("RECEIVE_COFFEEHOUSES_FAILURE");

