name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: [ tests ]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          CI='' npm run build
      
      - name: Share build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build

      - name: Ls
        run: ls -al

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Update image
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.SSH_TOKEN }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          ssh -i "$HOME/.ssh/key" ${{ secrets.USER }}@${{ secrets.HOST }} "./update.sh frontend"
